#!/usr/bin/env python3
"""Build a browser interaction coverage matrix from local capture evidence.

The script can consume HAR files and JSON capture summaries generated by local
Playwright/Burp tooling. With no evidence it emits `runtime_missing` or
`planned_only`; it never pretends that dynamic validation happened.
"""
from __future__ import annotations
import argparse, json, re
from pathlib import Path
from typing import Any

REQUIRED_ACTIONS = [
    'open_page', 'click_links_buttons', 'expand_menu_dropdown', 'hover_dropdown',
    'switch_tab', 'open_modal', 'scroll_bottom', 'search', 'change_filter',
    'paginate', 'safe_form_validation', 'safe_empty_upload_ui', 'mutate_path_query_hash',
    'refresh_deep_route', 'visit_error_pages', 'switch_role', 'switch_tenant'
]

JS_RE = re.compile(r"\.m?js(?:\?|$)", re.I)
API_RE = re.compile(r"/(?:api|graphql|rpc|admin|internal|v\d+|legacy|old|beta)/", re.I)
WS_RE = re.compile(r"^(?:ws|wss)://|/socket|/ws|graphql", re.I)
SENSITIVE_HEADERS = {'authorization', 'cookie', 'set-cookie', 'x-api-key', 'proxy-authorization'}

def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding='utf-8', errors='ignore'))
    except Exception as exc:
        return {'_load_error': f'{exc.__class__.__name__}: {exc}'}

def redacted_url(url: str) -> str:
    return re.sub(r"(?i)(token|secret|password|key|session|auth)=([^&#]+)", r"\1=<redacted>", url)

def har_entries(obj: Any) -> list[dict[str, Any]]:
    if isinstance(obj, dict) and isinstance(obj.get('log'), dict):
        entries = obj.get('log', {}).get('entries') or []
        return entries if isinstance(entries, list) else []
    return []

def extract_har(path: Path) -> dict[str, Any]:
    obj = load_json(path)
    rows=[]; chunks=set(); apis=set(); sockets=set()
    for e in har_entries(obj):
        req = e.get('request') if isinstance(e, dict) else {}
        resp = e.get('response') if isinstance(e, dict) else {}
        url = req.get('url') if isinstance(req, dict) else None
        method = req.get('method') if isinstance(req, dict) else 'UNKNOWN'
        status = resp.get('status') if isinstance(resp, dict) else None
        if not isinstance(url, str):
            continue
        rurl = redacted_url(url)
        if JS_RE.search(url): chunks.add(rurl)
        if API_RE.search(url): apis.add(rurl)
        if WS_RE.search(url): sockets.add(rurl)
        rows.append({'action': 'network_observed', 'page': rurl.split('?')[0], 'method': method, 'status': status, 'har': str(path), 'new_chunk': bool(JS_RE.search(url)), 'new_api': bool(API_RE.search(url)), 'websocket_sse_graphql': bool(WS_RE.search(url))})
    return {'rows': rows, 'chunks': sorted(chunks), 'apis': sorted(apis), 'sockets': sorted(sockets)}

def extract_capture_json(path: Path) -> dict[str, Any]:
    obj = load_json(path)
    rows=[]; roles=set(); tenants=set(); actions=set(); chunks=set(); apis=set(); sockets=set()
    if isinstance(obj, dict):
        for cap in obj.get('captures') or []:
            if isinstance(cap, dict):
                role = cap.get('role'); tenant = cap.get('tenant')
                if role: roles.add(str(role))
                if tenant: tenants.add(str(tenant))
                for art in cap.get('artifacts') or []:
                    if isinstance(art, dict) and str(art.get('type')) == 'har':
                        # Path may be relative to skill root; only parse when directly accessible.
                        hp = Path(art.get('path', ''))
                        if hp.exists():
                            h = extract_har(hp); rows.extend(h['rows']); chunks.update(h['chunks']); apis.update(h['apis']); sockets.update(h['sockets'])
                rows.append({'action': 'open_page', 'page': cap.get('url') or obj.get('url') or '', 'role': role, 'tenant': tenant, 'browser_executed': cap.get('browser_executed'), 'evidence': str(path)})
                if cap.get('browser_executed'):
                    actions.add('open_page')
        for inter in obj.get('interactions') or obj.get('coverage_rows') or []:
            if isinstance(inter, dict):
                action = str(inter.get('action') or inter.get('operation') or 'unknown')
                actions.add(action)
                if inter.get('role'): roles.add(str(inter.get('role')))
                if inter.get('tenant'): tenants.add(str(inter.get('tenant')))
                rows.append({**inter, 'evidence': str(path)})
    return {'rows': rows, 'roles': sorted(roles), 'tenants': sorted(tenants), 'actions': sorted(actions), 'chunks': sorted(chunks), 'apis': sorted(apis), 'sockets': sorted(sockets)}

def build(args: argparse.Namespace) -> dict[str, Any]:
    rows=[]; actions=set(); roles=set(); tenants=set(); chunks=set(); apis=set(); sockets=set(); evidence=[]; gaps=[]
    for h in args.har or []:
        p=Path(h)
        if not p.exists():
            gaps.append({'missing_har': h}); continue
        evidence.append(str(p)); r=extract_har(p); rows.extend(r['rows']); chunks.update(r['chunks']); apis.update(r['apis']); sockets.update(r['sockets'])
        if r['rows']: actions.add('open_page')
    for c in args.capture_json or []:
        p=Path(c)
        if not p.exists():
            gaps.append({'missing_capture_json': c}); continue
        evidence.append(str(p)); r=extract_capture_json(p); rows.extend(r['rows']); actions.update(r['actions']); roles.update(r['roles']); tenants.update(r['tenants']); chunks.update(r['chunks']); apis.update(r['apis']); sockets.update(r['sockets'])
    # Optional manual declared coverage, useful when Playwright exporter emits a small action list.
    for a in args.action or []:
        actions.add(a)
        rows.append({'action': a, 'page': args.page or '', 'manual_declaration': True, 'requires_artifact_for_confirmation': True})
    if args.role:
        roles.update(args.role)
    if args.tenant:
        tenants.update(args.tenant)
    for required in REQUIRED_ACTIONS:
        if required not in actions:
            gaps.append({'missing_action': required, 'impact': 'cannot claim full browser interaction coverage without this action or explicit not_applicable reason'})
    runtime_status = 'browser_evidence_present' if evidence and rows and (actions or chunks or apis) else 'runtime_missing'
    if args.planned_only:
        runtime_status = 'planned_only'
    elif evidence and gaps:
        runtime_status = 'partial_evidence'
    role_tenant = bool(roles) and bool(tenants)
    coverage_percent = round(100 * (len([a for a in REQUIRED_ACTIONS if a in actions]) / len(REQUIRED_ACTIONS)), 2)
    dynamic_claim_allowed = runtime_status == 'browser_evidence_present' and coverage_percent >= 60 and role_tenant
    if runtime_status in {'runtime_missing','planned_only'}:
        gaps.append({'runtime_missing': True, 'reason': args.runtime_reason or 'no local browser/HAR/capture evidence provided'})
    if not role_tenant:
        gaps.append({'missing': 'role_tenant_matrix', 'impact': 'authz/IDOR/tenant/admin findings cannot be confirmed'})
    return {
        'schema_version': 'browser_interaction_coverage_v1',
        'non_destructive': True,
        'runtime_status': runtime_status,
        'runtime_reason': args.runtime_reason or '',
        'required_actions': REQUIRED_ACTIONS,
        'observed_actions': sorted(actions),
        'coverage_rows': rows,
        'evidence_files': evidence,
        'new_chunks': sorted(chunks),
        'new_apis': sorted(apis),
        'websocket_sse_graphql': sorted(sockets),
        'roles': sorted(roles),
        'tenants': sorted(tenants),
        'role_tenant_matrix_present': role_tenant,
        'coverage_percent': coverage_percent,
        'evidence_gaps': gaps,
        'dynamic_claim_allowed': dynamic_claim_allowed,
        'promotion_policy': 'dynamic validation may be claimed only when browser evidence exists, role/tenant matrix exists, and required interactions are covered or explicitly justified'
    }

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--har', action='append')
    ap.add_argument('--capture-json', action='append')
    ap.add_argument('--action', action='append')
    ap.add_argument('--role', action='append')
    ap.add_argument('--tenant', action='append')
    ap.add_argument('--page')
    ap.add_argument('--planned-only', action='store_true')
    ap.add_argument('--runtime-reason', default='')
    ap.add_argument('--out')
    args = ap.parse_args()
    result = build(args)
    text = json.dumps(result, ensure_ascii=False, indent=2)
    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(text + '\n', encoding='utf-8')
    print(text)
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
