#!/usr/bin/env python3
from __future__ import annotations
import json, sys
from pathlib import Path
root = Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()
errors=[]
for d in sorted(root.glob('[0-9][0-9]-*')):
    if d.is_dir() and not (d/'SKILL.md').exists():
        errors.append(f'missing SKILL.md: {d.relative_to(root)}')
for p in root.rglob('*'):
    if p.name == '__pycache__' or p.suffix == '.pyc' or p.name in {'.DS_Store','Thumbs.db'} or p.suffix in {'.tmp','.bak','.swp'}:
        errors.append(f'forbidden cache file: {p.relative_to(root)}')
required = ['docs/CAPABILITY_INDEX.md','docs/DOCUMENT_MAPPING_MATRIX.md','docs/ROUTING_TABLE.md','docs/QUALITY_GATE_SPEC.md','templates/evidence-manifest.json','schemas/evidence-manifest.schema.json','tests/trigger-test-cases.json','12-js-skills-extreme-reviewer/SKILL.md','data/js_collection_points.json','data/js_audit_capabilities.json','data/js_severe_vulnerability_chains.json','data/info_js_linkage_matrix.json','data/script_inventory_expected.json','templates/extreme-skills-review-report.md','schemas/extreme-review.schema.json','scripts/extreme_skills_review.py','scripts/verify_extreme_review_assets.py','13-js-skills-second-pass-reverse-auditor/SKILL.md','scripts/second_pass_reverse_audit.py','scripts/verify_second_pass_assets.py','schemas/second-pass-review.schema.json','templates/second-pass-reverse-audit-report.md','docs/SECOND_PASS_REVERSE_AUDIT.md','knowledge/second-pass-js-audit-fidelity-rules.md','data/second_pass_original_conclusion_checks.json','data/second_pass_js_collection_points.json','data/second_pass_js_audit_capabilities.json','data/second_pass_severe_js_chains.json','data/second_pass_unconventional_js_audit_points.json','data/second_pass_score_rules.json','14-js-skills-evidence-court/SKILL.md','scripts/final_evidence_court_audit.py','scripts/verify_final_court_assets.py','schemas/final-evidence-court.schema.json','templates/final-evidence-court-report.md','docs/FINAL_EVIDENCE_COURT.md','knowledge/final-evidence-court-rules.md','data/final_court_prior_conclusion_trial.json','data/final_court_js_collection_incidents.json','data/final_court_pseudo_capabilities.json','data/final_court_severe_miss_risks.json','data/final_court_engineering_autopsy.json','data/final_court_score_penalty_rules.json','data/final_court_p0_nonnegotiable.json','data/final_court_final_findings.json','15-js-top-tier-collection-analysis-audit/SKILL.md','scripts/js_top_tier_collect.py','scripts/js_top_tier_analyze.py','scripts/js_top_tier_quality_gate.py','scripts/js_runtime_evidence_bridge.py','scripts/js_role_tenant_diff.py','scripts/js_top_tier_report_generator.py','scripts/run_js_top_tier_fixture_tests.py','scripts/verify_js_top_tier_assets.py','scripts/backends/js/babel_extract.mjs','scripts/backends/js/typescript_extract.mjs','schemas/js-top-tier-ledger.schema.json','schemas/js-top-tier-finding.schema.json','templates/js-top-tier-report.md','knowledge/js-top-tier-audit-playbook.md','data/js_top_tier_collectors.json','data/js_top_tier_detectors.json','data/js_top_tier_quality_caps.json','data/js_top_tier_runtime_requirements.json','docs/JS_TOP_TIER_COLLECTION_ANALYSIS_AUDIT.md','fixtures/js-top-tier-samples/app/index.html']
for r in required:
    if not (root/r).exists(): errors.append(f'missing required file: {r}')
print(json.dumps({'ok': not errors, 'errors': errors}, ensure_ascii=False, indent=2))
raise SystemExit(1 if errors else 0)
