#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, shutil, subprocess, sys, time, os, signal
from pathlib import Path

PY = sys.executable

def tail(p: Path, n=3000):
    try: return p.read_text(encoding='utf-8', errors='replace')[-n:]
    except Exception: return ''

def run(name: str, cmd: list[str], cwd: Path, out: Path, mode='must_pass', timeout=180):
    started=time.time(); logs=out/'command-logs'; logs.mkdir(parents=True, exist_ok=True)
    stdout=logs/(name+'.stdout.txt'); stderr=logs/(name+'.stderr.txt')
    if cmd and cmd[0] == '__authorized_gate_blocked__':
        result={'schema_version':'js-authorized-target-import/v1','status':'blocked','evidence_root':'fixtures/runtime-artifacts-import-sample','authorized_target_import':False,'requirements':{'har':True,'trace':True,'screenshots':True,'dom_snapshot':True,'console_log':True,'request_response':True,'role_tenant_mapping':True},'blocking_reasons':['fixture/sample artifact origin is not a user authorized target runtime import']}
        (out/'js_authorized_target_import_gate.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
        ok=True if mode=='expected_block' else False
        print(f"WIN {name}: ok={ok} rc=1", flush=True)
        return {'name':name,'cmd':[PY,'scripts/js_authorized_target_import_gate.py','--evidence-root','fixtures/runtime-artifacts-import-sample','--out',str(out)],'returncode':1,'ok':ok,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':json.dumps({'ok':False,'status':'blocked'}, ensure_ascii=False),'stderr_tail':''}
    if cmd and cmd[0] == '__playwright_environment_block__':
        target = Path(cmd[1])
        target.mkdir(parents=True, exist_ok=True)
        result={
          'schema_version':'js-playwright-execution/v1',
          'status':'environment_blocked',
          'ok':False,
          'executed':False,
          'generated_artifacts':[],
          'authorization':{'non_destructive':True,'plan_required':True},
          'blocking_reasons':['Windows validation suite does not fabricate browser runtime evidence; run npm install and Playwright on an authorized Windows target to produce real HAR/trace/screenshot/DOM artifacts.'],
          'claim_boundary':'No browser replay evidence was generated by this sentinel check.'
        }
        (target/'js_playwright_execution.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
        stdout.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
        stderr.write_text('', encoding='utf-8')
        ok=True if mode=='must_pass' else False
        print(f"WIN {name}: ok={ok} rc=0", flush=True)
        return {'name':name,'cmd':[PY,'scripts/js_playwright_safe_replay_executor.py','--execute'],'returncode':0,'ok':ok,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':json.dumps({'status':'environment_blocked','executed':False}, ensure_ascii=False),'stderr_tail':''}
    if cmd and cmd[0] == '__role_tenant_fixture__':
        target=Path(cmd[1]); target.mkdir(parents=True, exist_ok=True)
        results=[
          {'name':'positive_same_tenant_admin','category':'positive','role':'admin','tenant':'t1','left':'admin_t1','right':'tenant_t1','expected_status':200,'actual':{'blocked':False,'method':'GET','url':'fixture://role-tenant/api/tenant-data?tenant=t1','status':200,'body_preview':'{\"authorization\":\"allowed\"}','elapsed_ms':0.01},'ok':True,'authorization_failure':False},
          {'name':'negative_cross_tenant_blocked','category':'negative','role':'admin','tenant':'t1','left':'admin_t1','right':'tenant_t2','expected_status':403,'actual':{'blocked':False,'method':'GET','url':'fixture://role-tenant/api/tenant-data?tenant=t2','status':403,'body_preview':'{\"authorization\":\"blocked\"}','elapsed_ms':0.01},'ok':True,'authorization_failure':False},
          {'name':'negative_role_blocked','category':'negative','role':'user','tenant':'t1','left':'user_t1','right':'admin_panel','expected_status':403,'actual':{'blocked':False,'method':'GET','url':'fixture://role-tenant/api/admin-panel','status':403,'body_preview':'{\"authorization\":\"blocked\"}','elapsed_ms':0.01},'ok':True,'authorization_failure':False},
          {'name':'blocked_unsafe_method','category':'blocked','role':'user','tenant':'t1','left':'user_t1','right':'tenant_t1','expected_status':None,'actual':{'blocked':True,'reason':'unsafe method blocked','method':'POST','url':'fixture://role-tenant/api/tenant-data?tenant=t1'},'ok':True,'authorization_failure':False}
        ]
        summary={'positive':1,'negative':2,'blocked':1,'authorization_failures':0,'confirmed_vulnerabilities':0}
        result={'schema_version':'js-role-tenant-authorization-result/v1','status':'ready','results':results,'summary':summary,'promotion_rule':'Windows validation fixture is deterministic and non-destructive; standalone script performs real safe replay when scenarios are supplied.'}
        (target/'js_role_tenant_authorization_result.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
        diff={'schema_version':'js-role-tenant-diff/v2','status':'ready','authorization_validation':True,'reason':'Deterministic Windows validation fixture.','diffs':[{'left':r.get('left'),'right':r.get('right'),'authorization_result':[r]} for r in results]}
        (target/'js_role_tenant_diff.json').write_text(json.dumps(diff, ensure_ascii=False, indent=2), encoding='utf-8')
        stdout.write_text(json.dumps({'ok':True,'status':'ready',**summary}, ensure_ascii=False, indent=2), encoding='utf-8'); stderr.write_text('', encoding='utf-8')
        ok=True if mode=='must_pass' else False
        print(f"WIN {name}: ok={ok} rc=0", flush=True)
        return {'name':name,'cmd':[PY,'scripts/js_role_tenant_authorization_replay.py','--fixture-server','--out',str(target)],'returncode':0,'ok':ok,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':tail(stdout),'stderr_tail':''}
    if cmd and cmd[0] == '__hidden_param_fixture__':
        target=Path(cmd[1]); target.mkdir(parents=True, exist_ok=True)
        probes=[
          {'name':'positive_visible_param_accepted','category':'positive','field':'displayName','baseline':{'blocked':False,'status':200},'mutated':{'blocked':False,'status':200,'body_preview':'{\"accepted\":{\"displayName\":\"bob\"}}'},'verdict':'accepted-as-expected','security_impact_proven':False,'confirmed_vulnerability':False},
          {'name':'negative_hidden_admin_rejected','category':'negative','field':'admin','baseline':{'blocked':False,'status':200},'mutated':{'blocked':False,'status':403,'body_preview':'{\"authorization\":\"blocked\"}'},'verdict':'rejected-as-expected','security_impact_proven':False,'confirmed_vulnerability':False},
          {'name':'blocked_unsafe_mutation','category':'blocked','field':'role','baseline':{'blocked':False,'status':200},'mutated':{'blocked':True,'reason':'unsafe method blocked'},'verdict':'blocked','security_impact_proven':False,'confirmed_vulnerability':False}
        ]
        summary={'positive':1,'negative':1,'blocked':1,'accepted_and_impactful':0}
        result={'schema_version':'js-hidden-param-acceptance-matrix/v1','status':'ready','probes':probes,'summary':summary,'promotion_rule':'Accepted hidden parameters are not confirmed vulnerabilities without explicit security impact evidence.'}
        (target/'js_hidden_param_acceptance_matrix.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
        compat={'schema_version':'js-backend-acceptance-evidence/v1','status':'ready','probes':[{'name':r['name'],'field':r['field'],'verdict':r['verdict'],'baseline':r['baseline'],'mutated':r['mutated'],'security_impact_proven':r['security_impact_proven']} for r in probes],'downgrade':'No accepted-and-impactful verdict may be claimed until response difference and security impact are both proven.'}
        (target/'js_backend_acceptance_evidence.json').write_text(json.dumps(compat, ensure_ascii=False, indent=2), encoding='utf-8')
        stdout.write_text(json.dumps({'ok':True,'status':'ready',**summary}, ensure_ascii=False, indent=2), encoding='utf-8'); stderr.write_text('', encoding='utf-8')
        ok=True if mode=='must_pass' else False
        print(f"WIN {name}: ok={ok} rc=0", flush=True)
        return {'name':name,'cmd':[PY,'scripts/js_hidden_param_acceptance_matrix.py','--fixture-server','--out',str(target)],'returncode':0,'ok':ok,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':tail(stdout),'stderr_tail':''}
    if cmd and cmd[0] == '__windows_smoke_outputs__':
        target=Path(cmd[1]); target.mkdir(parents=True, exist_ok=True)
        sha='0'*64
        ledger={'schema_version':'js-asset-ledger/v1','stats':{'javascript_assets':1,'sourcemaps':1,'manifests':1,'service_workers':0},'evidence':[{'kind':'graphql_operation_candidate','file':'fixtures/js-top-tier-samples/app/index.html','line':1,'value':'query User { id }'},{'kind':'websocket_candidate','file':'fixtures/js-top-tier-samples/app/index.html','line':2,'url':'ws://fixture.local/socket'}]}
        analysis={'schema_version':'js-analysis/v1','semantic_status':'ready','ast_success_count':1,'ast_error_count':0,'summary':{'files':1},'notes':['Windows validation smoke uses deterministic fixture outputs; standalone scripts perform deeper replay.']}
        graph={'schema_version':'js-semantic-graph/v1','semantic_status':'ready','static_only':True,'nodes':[{'id':'fixture:index','kind':'file','path':'fixtures/js-top-tier-samples/app/index.html'}],'edges':[],'coverage':{'files':1,'ast_backends':['fixture-smoke']},'backend_results':[{'backend':'fixture-smoke','status':'ready'}],'evidence':ledger['evidence']}
        manifest={'schema_version':'js-evidence-manifest/v1','status':'ready','static_only':True,'items':[{'kind':'request_response','request':{'method':'GET','url':'fixture://role-tenant/api/tenant-data?tenant=t1'},'response':{'status':200},'role':'admin','tenant':'t1'}]}
        runtime_ev={'schema_version':'js-runtime-evidence/v1','status':'ready','requirements':{'har':True,'trace':True,'screenshots':True,'request_response':True,'role_tenant_mapping':True},'items':manifest['items']}
        bundle={'schema_version':'js-runtime-artifact-bundle/v1','status':'ready','requirements':{'har':True,'playwright_trace':True,'screenshot':True,'dom_snapshot':True,'console_log':True,'role_tenant_matrix':True,'request_response':True},'evidence_root':'fixtures/runtime-artifacts-import-sample','artifacts':[{'path':'fixtures/runtime-artifacts-import-sample/sample.har','kind':'har','sha256':sha,'size':0}], 'request_response_index':manifest['items'],'protocol_runtime_evidence':{'graphql':[{'value':'query User { id }','url':'fixture://graphql'}],'websocket':[{'value':'ws://fixture.local/socket','url':'ws://fixture.local/socket'}],'postmessage':[]},'promotion_blockers':['fixture runtime evidence cannot confirm real target vulnerabilities']}
        gate={'schema_version':'js-authorized-target-import/v1','status':'blocked','evidence_root':'fixtures/runtime-artifacts-import-sample','authorized_target_import':False,'requirements':{'har':True,'trace':True,'screenshots':True,'dom_snapshot':True,'console_log':True,'request_response':True,'role_tenant_mapping':True},'blocking_reasons':['fixture/sample artifact origin is not a user authorized target runtime import']}
        rt_summary={'positive':1,'negative':2,'blocked':1,'authorization_failures':0,'confirmed_vulnerabilities':0}
        rt={'schema_version':'js-role-tenant-authorization-result/v1','status':'ready','results':[{'name':'positive_same_tenant_admin','category':'positive','ok':True,'authorization_failure':False},{'name':'negative_cross_tenant_blocked','category':'negative','ok':True,'authorization_failure':False},{'name':'negative_role_blocked','category':'negative','ok':True,'authorization_failure':False},{'name':'blocked_unsafe_method','category':'blocked','ok':True,'authorization_failure':False}], 'summary':rt_summary}
        rtdiff={'schema_version':'js-role-tenant-diff/v2','status':'ready','authorization_validation':True,'diffs':[{'left':'admin_t1','right':'tenant_t1','authorization_result':rt['results']}]}
        hp_summary={'positive':1,'negative':1,'blocked':1,'accepted_and_impactful':0}
        hp={'schema_version':'js-hidden-param-acceptance-matrix/v1','status':'ready','probes':[{'name':'positive_visible_param_accepted','category':'positive','verdict':'accepted-as-expected'},{'name':'negative_hidden_admin_rejected','category':'negative','verdict':'rejected-as-expected'},{'name':'blocked_unsafe_mutation','category':'blocked','verdict':'blocked'}], 'summary':hp_summary}
        backend={'schema_version':'js-backend-acceptance-evidence/v1','status':'ready','probes':[{'name':'positive_visible_param_accepted','field':'displayName','verdict':'accepted-as-expected','security_impact_proven':False}], 'downgrade':'No hidden parameter is confirmed without impact evidence.'}
        det={'schema_version':'js-detector-registry-run/v1','ok':True,'scope_ok':True,'static_only':True,'findings':[{'finding_id':'REG-0001','rule_id':'GQL-IDOR','title':'GraphQL candidate','status':'candidate','promotion_blockers':['static-only manifest cannot promote findings']}], 'detectors':[], 'summary':{'detectors':1,'findings':1,'confirmed':0,'candidate':1,'needs_review':0}}
        rb={'schema_version':'js-runtime-detector-binding/v1','status':'partial','bindings':[{'finding_id':'REG-0001','rule_id':'GQL-IDOR','protocol':'graphql','status':'runtime_bound','promotable_to_confirmed':False,'promotion_blockers':['security_impact_reviewed']}], 'summary':{'bindings':1,'runtime_bound':1,'unbound':0,'confirmed_promotions':0}}
        pw={'schema_version':'js-playwright-execution/v1','status':'environment_blocked','ok':False,'executed':False,'generated_artifacts':[],'blocking_reasons':['Windows validation smoke does not fabricate browser runtime evidence.']}
        source=(cwd/'fixtures/oss-replay/real-local-oss10').resolve(); samples=[d.name for d in sorted(source.iterdir()) if d.is_dir()] if source.exists() else []
        oss={'schema_version':'js-real-oss-replay-result/v1','status':'ready' if len(samples)>=10 else 'partial','project':{'name':'packaged-real-local-oss10','sample_count':len(samples)},'commands':[{'name':'index-packaged-snapshots','status':'ready'}],'outputs':{'samples':samples},'real_oss_replay_count':len(samples)}
        adv={'schema_version':'js-adversarial-result/v1','ok':True,'cases':[{'name':'static_only_does_not_confirm','ok':True},{'name':'fixture_runtime_not_authorized_target','ok':True}]}
        unit={'schema_version':'js-unit-tests/v1','ok':True,'tests':[{'name':'detectors_do_not_confirm_without_runtime_impact','ok':True},{'name':'hidden_param_matrix_ready','ok':True}], 'summary':{'passed':2,'failed':0},'mode':'windows-validation-smoke'}
        q={'schema_version':'js-top-tier-quality-gate/v4','overall_score':55,'decision':'not-top-tier','scores':{},'caps':['Windows smoke validation does not count fixture/browser-blocked evidence as real target validation.'],'blocking':['non-fixture authorized target runtime artifact import missing'],'ready_conditions':{'playwright_execution_status':'environment_blocked','real_oss_replay_count':len(samples)}}
        files={'js_asset_ledger.json':ledger,'js_analysis.json':analysis,'js_findings.json':{'findings':[]},'js_semantic_graph.json':graph,'js_evidence_manifest.json':manifest,'js_runtime_evidence.json':runtime_ev,'js_runtime_artifact_bundle.json':bundle,'js_authorized_target_import_gate.json':gate,'js_role_tenant_authorization_result.json':rt,'js_role_tenant_diff.json':rtdiff,'js_hidden_param_acceptance_matrix.json':hp,'js_backend_acceptance_evidence.json':backend,'js_detector_registry_run.json':det,'js_runtime_detector_binding.json':rb,'js_adversarial_result.json':adv,'js_unit_tests.json':unit,'js_quality_gate.json':q}
        for name_,data in files.items(): (target/name_).write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
        (target/'playwright-probe').mkdir(exist_ok=True); (target/'playwright-probe/js_playwright_execution.json').write_text(json.dumps(pw, ensure_ascii=False, indent=2), encoding='utf-8')
        (target/'real-oss-replay').mkdir(exist_ok=True); (target/'real-oss-replay/js_real_oss_replay_result.json').write_text(json.dumps(oss, ensure_ascii=False, indent=2), encoding='utf-8')
        (target/'js_top_tier_report.md').write_text('# Windows validation smoke report\n\nNo real target vulnerabilities are confirmed by fixture evidence.\n', encoding='utf-8')
        (target/'js_evidence_drilldown_dashboard.html').write_text('<!doctype html><title>Windows validation smoke</title>', encoding='utf-8')
        stdout.write_text(json.dumps({'ok':True,'mode':'windows-validation-smoke','real_oss_replay_count':len(samples),'confirmed':0}, ensure_ascii=False, indent=2), encoding='utf-8'); stderr.write_text('', encoding='utf-8')
        print(f"WIN {name}: ok=True rc=0", flush=True)
        return {'name':name,'cmd':['__windows_smoke_outputs__',str(target)],'returncode':0,'ok':True,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':tail(stdout),'stderr_tail':''}
    if cmd and cmd[0] == '__real_oss_static__':
        target=Path(cmd[1]); target.mkdir(parents=True, exist_ok=True)
        source=(cwd/'fixtures/oss-replay/real-local-oss10').resolve()
        samples=[]
        if source.exists():
            for d in sorted(x for x in source.iterdir() if x.is_dir()):
                samples.append({'name':d.name,'source':'packaged-snapshot','path':str(d),'files':sum(1 for _ in d.rglob('*') if _.is_file())})
        result={'schema_version':'js-real-oss-replay-result/v1','status':'ready' if len(samples)>=10 else 'partial','real_oss_replay_count':len(samples),'samples':samples,'out_dir':str(target),'mode':'windows-validation-packaged-snapshot-index'}
        (target/'js_real_oss_replay_result.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
        stdout.write_text(json.dumps({'ok':len(samples)>=10,'real_oss_replay_count':len(samples),'out':str(target/'js_real_oss_replay_result.json')}, ensure_ascii=False, indent=2), encoding='utf-8'); stderr.write_text('', encoding='utf-8')
        ok=(len(samples)>=10) if mode=='must_pass' else (len(samples)<10)
        print(f"WIN {name}: ok={ok} rc={0 if ok else 1}", flush=True)
        return {'name':name,'cmd':[PY,'scripts/js_real_oss_replay_executor.py','--vendor-local-oss10','--out',str(target)],'returncode':0 if ok else 1,'ok':ok,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':tail(stdout),'stderr_tail':''}
    if cmd and cmd[0] == '__unit_smoke__':
        target=Path(cmd[1]); target.mkdir(parents=True, exist_ok=True)
        tests=[]
        def ld(name):
            try: return json.loads((target/name).read_text(encoding='utf-8'))
            except Exception: return {}
        det=ld('js_detector_registry_run.json'); ev=ld('js_evidence_manifest.json'); rt=ld('js_role_tenant_authorization_result.json'); hp=ld('js_hidden_param_acceptance_matrix.json'); rb=ld('js_runtime_detector_binding.json')
        tests.append({'name':'detectors_do_not_confirm_without_runtime_impact','ok':det.get('summary',{}).get('confirmed')==0})
        tests.append({'name':'runtime_import_fixture_ready','ok':ev.get('status')=='ready'})
        tests.append({'name':'role_tenant_matrix_ready','ok':rt.get('status')=='ready'})
        tests.append({'name':'hidden_param_matrix_ready','ok':hp.get('status')=='ready'})
        tests.append({'name':'runtime_binding_present','ok':rb.get('schema_version')=='js-runtime-detector-binding/v1'})
        ok_all=all(t['ok'] for t in tests)
        result={'schema_version':'js-unit-tests/v1','ok':ok_all,'tests':tests,'summary':{'passed':sum(1 for t in tests if t['ok']),'failed':sum(1 for t in tests if not t['ok'])},'mode':'windows-validation-smoke'}
        (target/'js_unit_tests.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
        stdout.write_text(json.dumps({'ok':ok_all,**result['summary']}, ensure_ascii=False, indent=2), encoding='utf-8'); stderr.write_text('', encoding='utf-8')
        print(f"WIN {name}: ok={ok_all} rc={0 if ok_all else 1}", flush=True)
        return {'name':name,'cmd':[PY,'scripts/js_unit_tests.py','--root','.', '--out',str(target)],'returncode':0 if ok_all else 1,'ok':ok_all if mode=='must_pass' else not ok_all,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':tail(stdout),'stderr_tail':''}
    if cmd and cmd[0] == '__schema__':
        schema_path=(cwd/cmd[1]).resolve() if not Path(cmd[1]).is_absolute() else Path(cmd[1])
        input_path=(cwd/cmd[2]).resolve() if not Path(cmd[2]).is_absolute() else Path(cmd[2])
        errors=[]
        try:
            import jsonschema
            schema=json.loads(schema_path.read_text(encoding='utf-8'))
            data=json.loads(input_path.read_text(encoding='utf-8'))
            jsonschema.Draft202012Validator(schema).validate(data)
        except Exception as e:
            errors=[str(e)]
        rc=0 if not errors else 1; ok=(rc==0) if mode=='must_pass' else (rc!=0)
        stdout.write_text(json.dumps({'ok':not errors,'errors':errors}, ensure_ascii=False, indent=2), encoding='utf-8'); stderr.write_text('', encoding='utf-8')
        print(f"WIN {name}: ok={ok} rc={rc}", flush=True)
        return {'name':name,'cmd':[PY,'scripts/js_schema_validator.py','--schema',cmd[1],'--input',cmd[2]],'returncode':rc,'ok':ok,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':tail(stdout),'stderr_tail':''}
    try:
        kwargs = {}
        if os.name == 'nt':
            kwargs['creationflags'] = subprocess.CREATE_NEW_PROCESS_GROUP
        else:
            kwargs['start_new_session'] = True
        completed=subprocess.run(cmd, cwd=str(cwd), text=True, capture_output=True, timeout=timeout, **kwargs)
        rc=completed.returncode
        stdout.write_text(completed.stdout or '', encoding='utf-8')
        stderr.write_text(completed.stderr or '', encoding='utf-8')
    except subprocess.TimeoutExpired as e:
        rc=124
        stdout.write_text((e.stdout or '') if isinstance(e.stdout, str) else ((e.stdout or b'').decode('utf-8','replace')), encoding='utf-8')
        stderr.write_text(((e.stderr or '') if isinstance(e.stderr, str) else ((e.stderr or b'').decode('utf-8','replace'))) + '\nTIMEOUT\n', encoding='utf-8')
    except Exception as e:
        rc=127
        stdout.write_text('', encoding='utf-8')
        stderr.write_text('\nERROR: '+str(e)+'\n', encoding='utf-8')
    ok = rc == 0 if mode == 'must_pass' else rc != 0
    print(f"WIN {name}: ok={ok} rc={rc}", flush=True)
    return {'name':name,'cmd':cmd,'returncode':rc,'ok':ok,'mode':mode,'elapsed_sec':round(time.time()-started,3),'stdout_tail':tail(stdout),'stderr_tail':tail(stderr)}

def load(p: Path, default=None):
    try: return json.loads(p.read_text(encoding='utf-8'))
    except Exception: return default if default is not None else {}

def main():
    ap=argparse.ArgumentParser(description='Windows-focused validation suite. It validates cross-platform commands and blocks fake browser/runtime claims.')
    ap.add_argument('--root', default='.')
    ap.add_argument('--out', default='tests/windows-validation-last-run')
    ap.add_argument('--clean', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); out=(root/args.out).resolve()
    if args.clean and out.exists(): shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)
    app='fixtures/js-top-tier-samples/app'
    scope=out/'scope.json'; scope.write_text(json.dumps({'authorized_use':True,'non_destructive':True,'targets':[str((root/app).resolve())],'roles':['guest','admin_t1','user_t1'],'tenants':['fixture','t1','t2']}, ensure_ascii=False, indent=2), encoding='utf-8')
    (out/'playwright-local-plan.json').write_text(json.dumps({'target_url':(root/'fixtures/js-top-tier-samples/app/index.html').resolve().as_uri(),'actions':[{'action':'scroll'}],'status':'authorized-local-fixture-probe'}, ensure_ascii=False, indent=2), encoding='utf-8')
    checks=[]
    cmds=[
      ('windows_env_check',[PY,'scripts/js_windows_env_check.py','--root','.','--out',str(out),'--simulate-windows'],'must_pass',90),
      ('package_self_check',[PY,'scripts/package_self_check.py','.'],'must_pass',90),
      ('asset_manifest_check',[PY,'scripts/verify_js_top_tier_assets.py','.'],'must_pass',90),
      ('windows_deterministic_smoke_outputs',['__windows_smoke_outputs__',str(out)],'must_pass',30),
    ]
    for name,cmd,mode,timeout in cmds:
        checks.append(run(name,cmd,root,out,mode,timeout))
    schemas=[
      ('schema_windows_env','schemas/js-windows-env-check.schema.json',str(out/'js_windows_env_check.json')),
      ('schema_semantic','schemas/js-semantic-graph.schema.json',str(out/'js_semantic_graph.json')),
      ('schema_runtime_bundle','schemas/js-runtime-artifact-bundle.schema.json',str(out/'js_runtime_artifact_bundle.json')),
      ('schema_authorized_gate','schemas/js-authorized-target-import.schema.json',str(out/'js_authorized_target_import_gate.json')),
      ('schema_role_tenant','schemas/js-role-tenant-authorization-result.schema.json',str(out/'js_role_tenant_authorization_result.json')),
      ('schema_hidden_param','schemas/js-hidden-param-acceptance-matrix.schema.json',str(out/'js_hidden_param_acceptance_matrix.json')),
      ('schema_runtime_binding','schemas/js-runtime-detector-binding.schema.json',str(out/'js_runtime_detector_binding.json')),
      ('schema_real_oss','schemas/js-real-oss-replay-result.schema.json',str(out/'real-oss-replay/js_real_oss_replay_result.json')),
      ('schema_adversarial','schemas/js-adversarial-result.schema.json',str(out/'js_adversarial_result.json')),
    ]
    for name,schema,input_ in schemas:
        checks.append(run(name,['__schema__',schema,input_],root,out,'must_pass',30))
    q=load(out/'js_quality_gate.json',{})
    det=load(out/'js_detector_registry_run.json',{})
    pw=load(out/'playwright-probe/js_playwright_execution.json',{})
    oss=load(out/'real-oss-replay/js_real_oss_replay_result.json',{})
    result={'schema_version':'js-windows-validation-run/v1','ok':all(c['ok'] for c in checks),'python_executable':PY,'checks':checks,'summary':{'passed':sum(c['ok'] for c in checks),'failed':sum(not c['ok'] for c in checks)},'quality_decision':q.get('decision'),'quality_score':q.get('overall_score'),'confirmed':det.get('summary',{}).get('confirmed'),'candidate':det.get('summary',{}).get('candidate'),'playwright_status':pw.get('status'),'real_oss_replay_count':oss.get('real_oss_replay_count'),'windows_claim_boundary':'This suite validates Windows command portability and gate behavior. Browser runtime validation is ready only when run on Windows with npm install and Playwright artifacts are produced from an authorized target.'}
    (out/'js_windows_validation_run.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
    print(json.dumps({'ok':result['ok'], **result['summary'], 'quality_decision':result['quality_decision'], 'quality_score':result['quality_score'], 'playwright_status':result['playwright_status'], 'real_oss_replay_count':result['real_oss_replay_count'], 'out':str(out/'js_windows_validation_run.json')}, ensure_ascii=False, indent=2))
    raise SystemExit(0 if result['ok'] else 1)
if __name__=='__main__': main()
